### PR TITLE
readme file update.

### PR DESCRIPTION
**Pull request by baladkb**
Hi @hawksley, please check and merge My PR...

thanks :metal:

### CODE REVIEW

**Comment by hawksley** [comment]
Hi,

I will try to get to this soon. I am / have been traveling.

-Andrea

**Comment by baladkb** [comment]
Ok thanks @hawksley.

**Comment by baladkb** [comment]
@hawksley did You had a chance to see this [PR](https://github.com/hawksley/eleVR-Web-Player/pull/52)?

**Comment by baladkb** [comment]
@hawksley ?

**Pull request closed without merging**
