### PR TITLE
create `phoneVR` only when necessary in `player-webgl.js`

### PR DESCRIPTION
**Pull request by cvan**
small thing here I thought I'd fix. just trying to reduce the globals and move things to where they're used.

### CODE REVIEW

**Comment by hawksley** [comment]
Looks great. Thanks for cleaning this up!

**Comment by cvan** [comment]
thanks! though it looks like this was closed instead of merged

**Comment by hawksley** [comment]
Oh. Oops. Clearly clicked the wrong button by accident. I'll fix it when I get back to a computer. Probably not until tomorrow.

**Comment by hawksley** [comment]
Merged! Thanks for pointing out my mistake yesterday. :)

**Pull request merged**
