### PR TITLE
add ability to load external video URLs (via querystring, hash, postMessage)

### PR DESCRIPTION
**Pull request by cvan**
The code for handling the qs/hash/postMessage params is a bit verbose, but it handles the many possible cases well.

Let me know your thoughts. Thanks!

<hr>

## Sample usage

Query-string key-value params:
[`http://localhost:8080/?autoplay=1&video=http://cdn2.vrideo.com/prod_videos/v1/lSPg9ka_1080p_full.webm`](http://localhost:8080/?autoplay=1&video=http://cdn2.vrideo.com/prod_videos/v1/lSPg9ka_1080p_full.webm)

Hash key-value params:
[`http://localhost:8080/#video=http://cdn2.vrideo.com/prod_videos/v1/W7JUlEW_480p_full.mp4`](http://localhost:8080/#video=http://cdn2.vrideo.com/prod_videos/v1/W7JUlEW_480p_full.mp4)

Query-string JSON params:
[`http://localhost:8080/?{"video": "http://cdn2.vrideo.com/prod_videos/v1/3aM7Xd6_1080p_full.webm", "autoplay": "true", "projection": "mono"}`](http://localhost:8080/?{"video": "http://cdn2.vrideo.com/prod_videos/v1/3aM7Xd6_1080p_full.webm", "autoplay": "true", "projection": "mono"})

Hash JSON params:
[`http://localhost:8080/#{"autoplay": true, "video": "http://crossorigin.me/http://mobile.360heros.com/producers/4630608605686575/5579686187673361/video/video_7776b10db31f349ede5d253b7744e110.mp4"}`](http://localhost:8080/#{"autoplay": true, "video": "http://crossorigin.me/http://mobile.360heros.com/producers/4630608605686575/5579686187673361/video/video_7776b10db31f349ede5d253b7744e110.mp4"})

`postMessage` to the page from the JS console:
```
window.postMessage({video: 'http://cdn2.vrideo.com/prod_videos/v1/mYNVcD6_480p_full.mp4', autoplay: true, loop: true}, '*')
```

`postMessage` from an iframe:
```
data:text/html,<iframe id='i' src='http://localhost:8080' style='border: 0; position: absolute; left: 0; top: 0; height: 100%; width: 100%' allowfullscreen></iframe><script>setTimeout(function () { i.contentWindow.postMessage({video: 'http://cdn2.vrideo.com/prod_videos/v1/mYNVcD6_480p_full.mp4', autoplay: true, loop: true}, '*'); }, 300);</script>
```

### CODE REVIEW

**Comment by hawksley** [comment]
Can you add a section to the readme for this set of features? It's nice having an easy api, but I'm not sure that anyone would ever find it if they didn't read this pull request. :)

**Comment by hawksley** [comment]
ps. I've only ever written code to do a similar thing for a project once, and I don't know that I can claim to have been any less verbose, so I'm not necessarily the best code reviewer for this

**Comment by hawksley** [comment]
Also, the videos in your sample usage section are adorable.

**Comment by hawksley** [comment]
Anyhow, this LGTM, except for the comment about adding some documentation.

**Comment by hawksley** [comment]
Merging, will add "sample usage" from this pull request to the main readme for documentation for now.

**Comment by cvan** [comment]
thanks very much for reviewing and merging. was afk for a few days, so thanks for also adding the sample usage to the README. :)

**Pull request merged**
